local f = CreateFrame("Frame")
local function onload()
	print("hello player")
	button_loreshow:RegisterEvent("PLAYER_TARGET_CHANGED")
	button_loreshow:SetScript("OnEvent",Loreframe.onTargetChange)
	button_loreshow:SetScript("OnClick",Loreframe.showPannel)
	button_lorehide:SetScript("OnClick",Loreframe.hidePannel)
end
f:RegisterEvent("PLAYER_ENTERING_WORLD")
f:SetScript("OnEvent", onload)
Loreframe.onLogin()